spring:
  application:
    name: create-branch-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}

igrant:
  api-key: ${IGRANT_API_KEY}
  endpoint: ${IGRANT_ENDPOINT:https://demo-api.igrant.io/}
  presentation-request-id-bulk: ${IGRANT_PRESENTATION_REQUEST_ID_BULK:c67df445-27a4-49fa-af54-654f601a6688}
  presentation-request-id-npid: ${IGRANT_PRESENTATION_REQUEST_ID_NPID:1b0b960a-06fd-4b4f-9f84-c545d49c89f9}


management:
  server:
    port: 8181
  endpoints:
    web:
      exposure:
        include: 'prometheus,metrics,info,health'

server:
  port: 8080

---
spring:
  profiles:
    active: localhost

logging:
  level:
    no.brreg.createbranchbackend: debug

---

spring:
  profiles:
    active: azure