spring:
  application:
    name: create-branch-backend
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}

mattr:
  client-id: ${MATTR_CLIENT_ID}
  client-secret: ${MATTR_CLIENT_SECRET}
  tenant-url: ${MATTR_TENANT_URL}
  brreg-wallet-did: ${MATTR_BRREG_WALLET_DID}
  brreg-wallet-did-long: ${MATTR_BRREG_WALLET_DID_LONG}
  presentation-request-template-id: ${MATTR_PRESENTATION_REQUEST_TEMPLATE_ID:da734f1a-4e75-43c5-a53a-d8f593b6d975}
  callback-url: ${MATTR_CALLBACK_URL:https://webhook.site/0ba4afe8-4d75-42d8-85bf-5407658af340}

management:
  server:
    port: 8181
  endpoints:
    web:
      exposure:
        include: 'prometheus,metrics,info,health'

server:
  port: 8080

---
spring:
  profiles:
    active: localhost

logging:
  level:
    no.brreg.createbranchbackend: debug

---

spring:
  profiles:
    active: azure